Youtube-Page
jonathastavares/Youtube-Page pull request #2
Opened 2020-07-10 15:55 UTC by jonathastavares

#2 Pull Request - Changes requested were made.

2020-07-10 19:01 UTC, kitpao requested changes
# 👋 Hello Team,

🥇 You did a good work implementing the changes my colleague required, just some notes to be taken into account are marked below: ⬇️

🔍 I also noticed you used bootstrap already, nice! I would suggest you to try to practice manual css to get familiarized with the good practices first and you can get the most of learning 😌 
___
## Important:
* I have noticed you closed the previous pull request https://github.com/jonathastavares/Youtube-Page/pull/1 and merged the changes. This is not following the [GitHub flow](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/), in Github flow you should not merge until the changes are **_approved_** by the code reviewer, so you should work in the same pull request until a TSE approves the change. Remember the master is your sacred branch where everything is 100% prepared. Since this is the first project, you can continue working in this new pull request, but for next projects, if you do this you will be required to unmerge the pull request OR pass all your code to a new repo with a clean master.
___

### ♻️ Status: Your project requires some additional changes ♻️, please do them in this same pull request until a reviewer approves it, remember to submit another review request 🌿
__
##### 👉 If you have any doubts you can contact me in slack as @kitpao
##### 👉 You can find me in your completition form as Kitzia Paola Vidal Marroquin

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-07-10 19:01 UTC, kitpao commented on css/style.css
> +.dislike-button {
- [ ] **[OPTIONAL]** You did great joining the classes as the previous TSE suggested, but the objective of converting it to a class is to use the same class for both.
Example: 
In Html: 
    ```
    <span class="fa fa-thumbs-up voting-button"></span>
    <span class="fa fa-thumbs-down voting-button"></span>
    ```
    in CSS:
    ```
    .voting-button { ...}
    ```

2020-07-10 19:01 UTC, kitpao commented on index.html
>                  </li>
- [ ] **[MANDATORY]** Correct use of semantic tags: `<li>` tags (listed items) only belong inside `<ul>` tags (unordered lists), I understand they remained from changing the ul's into the correct semantic tags, but the li's must be changed as well. I see most of them could be changed into `<div>` tags

2020-07-10 21:38 UTC, jonathastavares commented
Requested changes were made. Thank you for the tips.

2020-07-11 00:40 UTC, kitpao approved these changes
# 👋 Hello again @jonathastavares and @bmuhamood!

🌟 You did an excellent job! You demostrate that you can do it without bootstrap classes, use the correct semantic tags and even corrected some extra features like the border in your subscribe button 😎

You only have **optional** changes, you can see them below: ⬇️

### 👏 Your project has been approved 👏
### 🚀 You may merge to master and submit the project completition form 
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao
##### 👉 You can find me in your completition form as Kitzia Paola Vidal Marroquin

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-07-11 00:40 UTC, kitpao commented on css/style.css
> +    float: center;
- [ ] **[Optional]** Sorry I didn't notice before, your searchbox is not centered, and that's because `float: center` doesn't exist, float only accepts right or left. The one that is positioning this item is the navbar's justify-content: space-between. It just looks to the right because the logo item is bigger than the sidelinks. One way you can correct this by making the sidelinks div bigger or the logo div smaller

2020-07-11 00:40 UTC, kitpao commented on css/style.css
> +    float: right;
since you are already using the navbar's justify-content: space-between, this `float: right` isn't doing anything, you can delete it

2020-07-13 14:57 UTC, merged